version: '3.2'

services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        volumes:
          - "./.mysql-data/db:/var/lib/mysql"
        restart: always
        ports:
          - ${MYSQL_PORT}:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
