version: '3.2'

services:
    mysql:
        image: mysql:8
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - "./my-db:/var/lib/mysql"
        restart: always
        ports:
          - ${MYSQL_PORT}:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
          MYSQL_USER: 'root'
    backend:
        build: .
        container_name: backend-container
        restart: always
        ports:
          - ${SERVER_PORT}:${SERVER_PORT}
        links:
           - mysql

volumes:
  my-db: